import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { ApiError } from "./errors.js";
import type { LabelAsset } from "./types.js";

export interface LocalAssetStorage {
  put(asset: LabelAsset, data: Buffer): void | Promise<void>;
  assertUploaded(asset: LabelAsset): void | Promise<void>;
  read(asset: LabelAsset): Buffer | Promise<Buffer>;
  delete(asset: LabelAsset): void | Promise<void>;
}

/** Volatile fallback used by unit tests and an explicitly in-memory API process. */
export class MemoryAssetStorage implements LocalAssetStorage {
  private readonly objects = new Map<string, Buffer>();

  put(asset: LabelAsset, data: Buffer): void {
    assertValidAssetBytes(asset, data);
    this.objects.set(asset.id, Buffer.from(data));
  }

  assertUploaded(asset: LabelAsset): void {
    const data = this.objects.get(asset.id);
    if (!data) throw uploadNotReady();
    assertValidAssetBytes(asset, data);
  }

  read(asset: LabelAsset): Buffer {
    this.assertUploaded(asset);
    return Buffer.from(this.objects.get(asset.id)!);
  }

  delete(asset: LabelAsset): void { this.objects.delete(asset.id); }
}

/**
 * Single-process disk-backed fallback for LOCAL_CLOUD_STORE_FILE development mode.
 * Production deployments should use S3-compatible object storage instead.
 */
export class FileAssetStorage implements LocalAssetStorage {
  readonly directory: string;

  constructor(directory: string) {
    this.directory = resolve(directory);
  }

  put(asset: LabelAsset, data: Buffer): void {
    assertValidAssetBytes(asset, data);
    mkdirSync(this.directory, { recursive: true });
    const filePath = this.pathFor(asset);
    const temporary = `${filePath}.tmp`;
    writeFileSync(temporary, data, { mode: 0o600 });
    try {
      if (existsSync(filePath)) rmSync(filePath, { force: true });
      renameSync(temporary, filePath);
    } finally {
      if (existsSync(temporary)) rmSync(temporary, { force: true });
    }
  }

  assertUploaded(asset: LabelAsset): void {
    const filePath = this.pathFor(asset);
    if (!existsSync(filePath)) throw uploadNotReady();
    assertValidAssetBytes(asset, readFileSync(filePath));
  }

  read(asset: LabelAsset): Buffer {
    this.assertUploaded(asset);
    return readFileSync(this.pathFor(asset));
  }

  delete(asset: LabelAsset): void { rmSync(this.pathFor(asset), { force: true }); }

  private pathFor(asset: LabelAsset): string {
    // Asset ids are UUIDs generated by the server; accepting anything else avoids path traversal.
    if (!/^[a-f0-9-]{36}$/i.test(asset.id)) throw new ApiError(400, "INVALID_ASSET_ID", "Asset identifier is invalid.");
    return join(this.directory, `${asset.id}.bin`);
  }
}

function assertValidAssetBytes(asset: LabelAsset, data: Buffer): void {
  if (data.byteLength !== asset.byteSize || createHash("sha256").update(data).digest("hex") !== asset.sha256) {
    throw new ApiError(400, "ASSET_UPLOAD_INVALID", "Uploaded asset content does not match the authorized upload.");
  }
}

function uploadNotReady(): ApiError {
  return new ApiError(400, "ASSET_UPLOAD_NOT_READY", "The asset upload is missing or not ready yet.");
}
