pub mod cloud_commands;
pub mod custom_preset_commands;
pub mod font_commands;
pub mod launch_commands;
pub mod print_commands;
pub mod recognition_commands;
pub mod recent_commands;
pub mod template_commands;
pub mod window_commands;
